### ISSUE TITLE
Build Hint

### ISSUE THREAD

**Issue by MrOplus** [ymmuse/sepcvpn#1]
Is there any build hint ?

**Comment by ymmuse** [comment]
Sorry for late reply. I have already update README file.

**Comment by MrOplus** [comment]
thanks , can you add NDK version , because Libev wont compile on r15c

```
/home/user/Desktop/sepcvpn/jni/libev/ev.c:3745: error: undefined reference to 'inotify_init1'
/home/user/Desktop/sepcvpn/jni/libev/ev.c:3745: error: undefined reference to 'inotify_init1'
collect2: error: ld returned 1 exit status
make: *** [/home/user/Desktop/sepcvpn/obj/local/armeabi-v7a/libjni.so] Error 1
make: Leaving directory `/home/user/Desktop/sepcvpn/jni'
```

**Comment by ymmuse** [comment]
I compiled on r13b. 
BTW. You could reference this
 https://github.com/android-ndk/ndk/issues/394
https://github.com/shadowsocks/libev/pull/2/commits/16c11ba8e5a26d10c6285b2b7613419ae5daaaeb
